<?php

namespace TWA\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{



    public function listByDateDesc()
        {
        #on appelle QueryBuilder pour construire des requètes
        $queryBuilder = $this->createQueryBuilder("a");
        #"a" est un alias

        #chainage de méthodes
        $articlesList = $queryBuilder
        ->addOrderBy('a.articleDate', 'DESC')
        /**
         * On pourrait spécifier d'autres
         * ->where('a.articleDate<:date')
         * ->setParameter('date', $dateMax)
         */
        ->getQuery()
        ->getArrayResult()
        ;
        #on return la liste que l'on vient de créer
        return $articlesList;

        #il faut maintenant remplacer la fonction find all par listByDateDesc dans
        # ArticleController

        }
}
